### ISSUE TITLE
/skfs WAR file gives 404

### ISSUE THREAD

**Issue by ashutoshkumarmishra560** [StrongKey/fido2#186]
Hi,

I have observed below issue on CentOS7 VM:

1. I start glassfish app server using the command systemctl start glassfishd
2. Glassfish starts successfully.
3. But when I access the URL https://idxlab.idx.com:8181/skfs/rest/application.wadl I get 404

This setup was working correctly and in expected manner till I restarted CentOS7 VM. 
Can you suggest any fix for this as I dont want to re-install the entire working setup.

**Comment by pattycakelol** [comment]
Hi @ashutoshkumarmishra560,

For your situation, two things come to mind.

1. GlassFish should be started when the vm is started, so there is no need to run a `systemctl start` command. An error may have occurred when starting GlassFish. Check your logs directory (`cd /usr/local/strongkey/payara5/glassfish/domains/domain1/logs/` or use the alias `aslg` for the same effect) and view the most recent logs in the server.log file to see if anything has gone wrong during start up. You may try to kill the glassfish process (`ps -ef | grep payara` then `kill -9 [pid]`), then start glassfish again with `service glassfishd start`.
2. If your server has dhcp enabled, your server may have been given a different ip after restarting. GlassFish may not start properly when the server's ip does not match that found in the server's hosts file entry. Take a look at your /etc/hosts and ensure that your server's ip matches its ip shown in the hosts file entry. If any changes are made you can perform a `service glassfishd restart`.

**Comment by ashutoshkumarmishra560** [comment]
Hi,

Appreciate your response on the same and pointing to the location of the logs. I am seeing below error in the logs:

[2022-04-18T14:43:25.329-0400] [Payara 5.2020.7] [WARNING] [NCLS-MON-00506] [javax.enterprise.system.tools.monitor] [tid: _ThreadID=16 _ThreadName=RunLevelControllerThread-1650307378775] [timeMillis: 1650307405329] [levelValue: 900] [[
  Error unregistering ProbeProvider
java.lang.NullPointerException
	at org.glassfish.flashlight.impl.provider.FlashlightProbeProviderFactory.unregisterProbeProvider(FlashlightProbeProviderFactory.java:377)
	at com.sun.ejb.containers.util.pool.AbstractPool.unregisterProbeProvider(AbstractPool.java:268)
	at com.sun.ejb.containers.util.pool.NonBlockingPool.close(NonBlockingPool.java:405)
	at com.sun.ejb.containers.StatelessSessionContainer.doConcreteContainerShutdown(StatelessSessionContainer.java:633)
	at com.sun.ejb.containers.BaseContainer.onShutdown(BaseContainer.java:4320)
	at org.glassfish.ejb.startup.EjbApplication.stop(EjbApplication.java:313)
	at org.glassfish.internal.data.EngineRef.stop(EngineRef.java:162)
	at com.sun.enterprise.v3.server.ApplicationLifecycle$3.actOn(ApplicationLifecycle.java:304)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:629)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:332)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]

[2022-04-18T14:43:25.359-0400] [Payara 5.2020.7] [SEVERE] [AS-WEB-GLUE-00192] [javax.enterprise.web] [tid: _ThreadID=16 _ThreadName=RunLevelControllerThread-1650307378775] [timeMillis: 1650307405359] [levelValue: 1000] [[
  Undeployment failed for context /skfe]]

[2022-04-18T14:43:25.359-0400] [Payara 5.2020.7] [SEVERE] [AS-WEB-GLUE-00192] [javax.enterprise.web] [tid: _ThreadID=16 _ThreadName=RunLevelControllerThread-1650307378775] [timeMillis: 1650307405359] [levelValue: 1000] [[
  Undeployment failed for context /skfs]]

[2022-04-18T14:43:25.359-0400] [Payara 5.2020.7] [SEVERE] [AS-WEB-GLUE-00192] [javax.enterprise.web] [tid: _ThreadID=16 _ThreadName=RunLevelControllerThread-1650307378775] [timeMillis: 1650307405359] [levelValue: 1000] [[
  Undeployment failed for context /replicationWAR]]

Request your inputs/suggestions.

**Comment by pattycakelol** [comment]
Hi @ashutoshkumarmishra560,

The error in your logs seems to be a result from a GlassFish error that has occurred, but it does not give me much info. Are there any errors above the log snippet that your provided? If so, please paste them here.

**Comment by ashutoshkumarmishra560** [comment]
I found these errors:

Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.7.payara-p3): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: IO Exception: null [90028-196]
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:318)
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:150)
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:172)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:225)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:809)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:256)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:772)
	... 59 more
Caused by: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: IO Exception: null [90028-196]
	at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:119)
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:138)
	... 64 more
Caused by: javax.resource.spi.ResourceAllocationException: Error in allocating a connection. Cause: Connection could not be allocated because: IO Exception: null [90028-196]
	at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:319)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:196)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:171)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:166)
	at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:113)
	... 65 more
Caused by: com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: IO Exception: null [90028-196]
	at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:103)
	at com.sun.enterprise.resource.pool.ConnectionPool.addResource(ConnectionPool.java:287)
	at com.sun.enterprise.resource.pool.ConnectionPool.createResourceAndAddToPool(ConnectionPool.java:1532)
	at com.sun.enterprise.resource.pool.ConnectionPool.createResources(ConnectionPool.java:957)
	at com.sun.enterprise.resource.pool.ConnectionPool.initPool(ConnectionPool.java:235)
	at com.sun.enterprise.resource.pool.ConnectionPool.internalGetResource(ConnectionPool.java:528)
	at com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:386)
	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:244)
	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:171)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:354)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:307)
	... 69 more
Caused by: com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: IO Exception: null [90028-196]
	at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:937)
	at com.sun.enterprise.resource.pool.ConnectionPool.createResource(ConnectionPool.java:1209)
	at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:98)
	... 79 more
Caused by: com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: IO Exception: null [90028-196]
	at com.sun.enterprise.resource.allocator.ConnectorAllocator.createResource(ConnectorAllocator.java:181)
	at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:920)
	... 81 more
Caused by: javax.resource.spi.ResourceAllocationException: Connection could not be allocated because: IO Exception: null [90028-196]
	at com.sun.gjc.spi.XAManagedConnectionFactory.createManagedConnection(XAManagedConnectionFactory.java:132)
	at com.sun.enterprise.resource.allocator.ConnectorAllocator.createResource(ConnectorAllocator.java:161)
	... 82 more
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: null [90028-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:192)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:188)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:351)
	at com.sun.gjc.spi.XAManagedConnectionFactory.createManagedConnection(XAManagedConnectionFactory.java:118)
	... 83 more
Caused by: java.lang.IllegalStateException: Reading from nio:/usr/local/strongkey/payara5/glassfish/domains/domain1/lib/databases/ejbtimer.mv.db failed; file length 442368 read length 1024 at 453612 [1.4.196/1]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:435)
	at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
	at org.h2.mvstore.Page.read(Page.java:190)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:1952)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:741)
	at org.h2.mvstore.Page.getChildPage(Page.java:217)
	at org.h2.mvstore.MVMap.binarySearch(MVMap.java:473)
	at org.h2.mvstore.MVMap.get(MVMap.java:455)
	at org.h2.mvstore.MVStore.getChunkIfFound(MVStore.java:958)
	at org.h2.mvstore.MVStore.getChunk(MVStore.java:935)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:1943)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:741)
	at org.h2.mvstore.Page.getChildPage(Page.java:217)
	at org.h2.mvstore.MVMap.binarySearch(MVMap.java:473)
	at org.h2.mvstore.MVMap.get(MVMap.java:455)
	at org.h2.mvstore.MVStore.getChunkIfFound(MVStore.java:958)
	at org.h2.mvstore.MVStore.getChunk(MVStore.java:935)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:1943)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:741)
	at org.h2.mvstore.Page.getChildPage(Page.java:217)
	at org.h2.mvstore.Cursor.fetchNext(Cursor.java:150)
	at org.h2.mvstore.Cursor.next(Cursor.java:50)
	at org.h2.mvstore.MVStore.loadChunkMeta(MVStore.java:695)
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:675)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:358)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	... 100 more
Caused by: java.io.EOFException
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:423)
	... 126 more
]]

[2022-04-18T14:56:26.121-0400] [Payara 5.2020.7] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-1650308158858] [timeMillis: 1650308186121] [levelValue: 1000] [[
  Exception while invoking class org.glassfish.ejb.startup.EjbApplication start method
java.lang.RuntimeException: EJB Timer Service is not available
	at com.sun.ejb.containers.BaseContainer.startApplication(BaseContainer.java:3937)
	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:168)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:283)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:364)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:623)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:332)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]

**Comment by pattycakelol** [comment]
Hi @ashutoshkumarmishra560,

Can you share the details of the vm that is being used.

Run `df -h` to get disk space details

**Comment by ashutoshkumarmishra560** [comment]
![skfs 404](https://user-images.githubusercontent.com/11361005/163863662-b1dd1024-c296-4b9b-8653-602cbfb6d9c4.png)
 The attached image has the details. VM is CentOS7

Appreciate your quick responses.

**Comment by pattycakelol** [comment]
Hi @ashutoshkumarmishra560,

Try performing the following steps:
1. Locate a copy of your `fidoserver.ear` file and store it somewhere on the file system with `strongkey` user ownership (maybe put it in strongkey's home directory, /usr/local/strongkey).
2. Log in as the `strongkey` user
3. Run `asadmin list-applications` to ensure that the fidoserver is deployed
4. Run `asadmin undeploy fidoserver` to undeploy the fidoserver
5. Run `rm -r /usr/local/strongauth/payara41/glassfish/domains/domain1/generated/policy` to enable a clean restart of the server
6. Run `sudo service glassfishd restart`. If any errors occur during a GlassFish restart, paste the logs here. You may need to reinstall GlassFish as something could have been corrupted- we will see.
7. Run `asadmin deploy /path/to/fidoserver.ear` to deploy the fidoserver again
8. If any error has occurred during the deployment, check the logs and paste them here. If not, run `asadmin list-applications` to ensure that the fidoserver has been deployed onto the server.

**Comment by ashutoshkumarmishra560** [comment]
Hi,

I performed the re-installation and now its back to normal. May be abrupt shutdown of VM might have caused the corruption. Thanks for your time and help.
