### ISSUE TITLE
Crash Report/Package Manager

### ISSUE THREAD

**Issue by VanishPoint13** [StrongKey/fido2#210]
App Name: Package Manager
Package Name: com.smartpack.packagemanager
App Version: v6.5
SDK Version: 31

Crash Report

java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at z1.k.c(:2)
	at y1.p$d.a(Unknown Source:6)
	at e2.c.run(:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

Steps to reproduce the issue:

**Comment by push2085** [comment]
Closing the as this is incomplete and nothing new was added to the issue
