### ISSUE TITLE
I cannot perform authentication with Apple's Touch ID.

### ISSUE THREAD

**Issue by Saebyeol98** [StrongKey/fido2#231]
Hello Strongkey Fido2 Developer @push2085  @arshadnoor 

I am implementing fido2 with your skfs v4.8.0 server.
In the process of using the example "fido policy" you provided, 
I tried to test FIDO registration and authentication with the TouchId embedded in the MAC.

First, I will explain the test scenario that I experimented with.

go to https://demo.strongkey.com/fidopolicy for policy options. 
User registered with TouchID with "minimal-any-hardware-authenticators" set

it's minimal-any-hardware-authenticators means did = 1

Registration was successful.

In the next course, I entered the name of the user I registered and selected minimal-any-hardware-authenticators for the same policy option to request authentication.

The authentication was successful, so I entered the login screen.

![image](https://user-images.githubusercontent.com/19588853/211245907-3cf59f3b-1e76-4e0a-91c4-9f56de9e7976.png)
![image](https://user-images.githubusercontent.com/19588853/211245939-8a2c0dc0-6996-4cc1-bd5d-e502490083d8.png)

Now in the same process, I'm going to use the same example on my server that was created with the SKFS FIDO server.
I tested the same scenario as above.

The registration was equally successful.

However, authentication failed due to an error in the authentication part.

In the same way, did = 1 was set and registration authentication was performed, but an error occurred during the authentication process.

The error log is as follows.

I am attaching the error log as below.

[forStrongkey.txt](https://github.com/StrongKey/fido2/files/10370516/forStrongkey.txt)

I look forward to your help.

I have something to tell you.
The domain address in the log has been changed to fidoserver1.demo.com for security purposes.

**Comment by ankit-psk** [comment]
@Saebyeol98,

We apologize, but https://demo.strongkey.com/fidopolicy is showing the 
wrong information in the "Minimal-Any-Hardware-Authenticators" - the 
actual policy was modified to make "requireCounters" optional - but the 
display in the web-application (which was - unfortunately - hard-coded 
by the developer with the initial policy - shows it to be mandatory) - 
see the attached image. So, the reason why it worked on our DEMO web-app 
is because Apple devices do NOT use counters - while the default SKFS 
policy, even for the Minimal policy - is that counters are required. (We 
will fix this incorrect display soon - thank you for bringing it to our 
attention).

If you change your policy to NOT require counters, you will be able to 
authenticate with the Apple device.

Arshad

**Comment by Saebyeol98** [comment]
@ankit-psk 
First of all, thank you for your quick reply.

As a result of my understanding of your answer,
Does DID = 1 mean that Counter should be modified to "optional" instead of "mandatory"?

As far as I know, the method of determining policy in skfs is saved only when it is installed as "install-skfs.sh".
Then do I have to run cleanup.sh and run "install-skfs.sh" again?

Reinstallation is too much of a process.
Is there a way to modify the policy separately?

I look forward to apply from you. 
Thank you.

**Comment by arshadnoor** [comment]
@Saebyeol98,

Yes, your understanding is correct. The installation process does 
install default policies; but you can update them - and perform a lot of 
other administrative tasks with this tool:

https://docs.strongkey.com/index.php/skfs-home/skfs-administration/skfs-skfsclient-cli/skfs-v3-api-usage

If you are using all the default passwords, here is how you can retrieve 
a policy - this one is showing it for DID=1:

https://docs.strongkey.com/index.php/skfs-home/skfs-administration/skfs-skfsclient-cli/skfs-v3-api-usage/get-policy-gp

Once you retrieve the policy, you can modify it (by changing 
"requireCounter" to "optional") and update the policy:

https://docs.strongkey.com/index.php/skfs-home/skfs-administration/skfs-skfsclient-cli/skfs-v3-api-usage/patch-policy-pp

Once again, we apologize that our documentation is not 100% clear, but 
we are working on it to improve it - you should see changes to it before 
the end of this week.

Hope this helps.

**Comment by Saebyeol98** [comment]
@arshadnoor 
Thank you for your quick response.

I tried to call Get Policy (GP) as shown in the document as below. But there's an error occurs.
Why did the error occur?

The domain address in the log has been changed to fidoserver1.demo.com for security purposes.

[root@fidoserver1 skfsclient]# java -jar skfsclient.jar R https://fidoserver1.demo.com:8181 1 REST PASSWORD svcfidouser Abcd1234! False 1 1

Copyright (c) 2001-2023 StrongAuth, Inc. All rights reserved.

REST Registration test with PASSWORD
*******************************
preregjson = 
{"svcinfo":{"did":1,"protocol":"FIDO2_0","authtype":"PASSWORD","svcusername":"svcfidouser","svcpassword":"Abcd1234!"},"payload":{"username":"False","displayname":"False","options":{},"extensions":"{}"}}

Calling preregister @ https://fidoserver1.demo.com:8181/skfs/rest/preregister
Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.strongkey.skfsclient.impl.rest.RestFidoRegister.register(RestFidoRegister.java:113)
        at FidoEngine.main(FidoEngine.java:165)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        ... 25 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 31 more
        
        
I look forward to apply from you.
Thank you.

**Comment by arshadnoor** [comment]
Your self-signed certificate for your SKFS installation is not in your 
Java truststore. You will need to import your TLS certificate - just the 
certificate; not your private key - into the truststore used by your JVM.

You can use keytool to import your TLS certificate. Assuming your 
certificate is in a file calld skfscert.pem or skfscert.crt - and your 
truststore is in the /usr/local/strongauth/certs or 
/usr/local/strongkey/certs use the following command:

keytool -import -file skfscert.pem -keystore truststore.jsk -alias skfs

This will prompt you for the truststore password - usually "changeit". 
You can verify that it is in the truststore using keytool again:

keytool -list -keystore truststore.jsk -alias skfs -v

If you see the details of your TLS certificate, you are good to go, and 
can run the command again without the PKIX Validation error.

**Comment by Saebyeol98** [comment]
@arshadnoor 
Thank you for your quick response.

I looked up the "truststore" file. The route you told me did not exist in my system. (/usr/local/strongkey/certs/truststore.jks)
So I looked up the jks files with the "find" command and found that there are two. Where should I put my certificate?
<img width="750" alt="image" src="https://user-images.githubusercontent.com/19588853/211695905-70838c9d-ab7a-43e5-b665-3680f3c42083.png">

Then, I have a certificate file that I got our server through let's encrypt.
I have 4 pem files of certificate file as below. Which file will you import?

<img width="704" alt="image" src="https://user-images.githubusercontent.com/19588853/211696494-d45daf73-9273-4f2c-aede-612e6d20c257.png">

If this part is solved, I feel like it's going to work.
I look forward to apply from you.
Thank you.

**Comment by pleung-strongkey** [comment]
Hi @Saebyeol98,
The truststore file can be found in the path: /usr/local/strongkey/certs/cacerts
Please modify the path that @arshadnoor provided and replace truststore.jks* with the cacerts path.

Also, please make sure that your java alias is pointing to the correct cacerts.
You can do this by running the command: ```alias java```

**Comment by Saebyeol98** [comment]
@pleung-strongkey 
Thank you for your quick response.

It's shows caerts is not directory it's file 
![image](https://user-images.githubusercontent.com/19588853/211699044-55a16f6f-f29b-4671-b892-1830bc39d324.png)

If I understand what you're saying,
Can I see the cacerts file same as truststore.jks?

That was my second question. Could you also tell me which pem file I should use?

I look forward to apply from you.
Thank you.

**Comment by Saebyeol98** [comment]
@arshadnoor @pleung-strongkey @ankit-psk 

Wow It really works very well!
After modifying the "policy" value and retesting, it is successfully authenticated.
I'll end the issue.
Thank you so much for helping me to operate normally.
Have a great day!
