### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by Cedric4real** [StrongKey/fido2#25]
Hello, I was trying to follow the installation guide for Strongkey/fido2 and at the sixth step, I get the following error "remote failure: Error occurred during deployment: Exception while loading the app : EJB Container initialization error." 
Here is the log of the installation: 

-------------------------------------------------------------------------------------------------------
Installing required linux packages (openjdk, unzip, libaio, ncurses-compat-libs[only applicable for Amazon Linux], rng-tools, curl) ... The installer will skip packages that do not apply or are already installed. Successful
Installing StrongKey FIDO2 Server (SKFS) ... Successful
Installing MariaDB... Successful
Installing Payara... Successful
Installing JDBC Driver... Successful
Installing OpenDJ... Successful
Restarting opendjd (via systemctl):                        [  OK  ]
Importing default users... Successful
Creating 10M SKFS Internal Database....done
Starting glassfishd (via systemctl):                       [  OK  ]
server.network-config.network-listeners.network-listener.http-listener-1.enabled=false
Command set executed successfully.
server.network-config.protocols.protocol.http-listener-2.http.request-timeout-seconds=7200
Command set executed successfully.
server.network-config.protocols.protocol.http-listener-2.ssl.ssl3-tls-ciphers=+TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,+TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,+TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,+TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,+TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,+TLS_DHE_RSA_WITH_AES_256_CBC_SHA
Command set executed successfully.
server.network-config.protocols.protocol.http-listener-2.ssl.ssl2-enabled=false
Command set executed successfully.
server.network-config.protocols.protocol.http-listener-2.ssl.ssl3-enabled=false
Command set executed successfully.
server.network-config.protocols.protocol.http-listener-2.ssl.tls-enabled=false
Command set executed successfully.
server.network-config.protocols.protocol.http-listener-2.ssl.tls11-enabled=false
Command set executed successfully.
server.network-config.protocols.protocol.http-listener-2.http.trace-enabled=false
Command set executed successfully.
server.network-config.protocols.protocol.http-listener-2.http.xpowered-by=false
Command set executed successfully.
JDBC connection pool SKFSPool created successfully.
Command create-jdbc-connection-pool executed successfully.
JDBC resource jdbc/strongkeylite created successfully.
Command create-jdbc-resource executed successfully.
server.resources.jdbc-connection-pool.SKFSPool.max-pool-size=1000
Command set executed successfully.
server.thread-pools.thread-pool.http-thread-pool.max-thread-pool-size=1000
Command set executed successfully.
server.thread-pools.thread-pool.http-thread-pool.min-thread-pool-size=10
Command set executed successfully.
Deleted 2 option(s)
Command delete-jvm-options executed successfully.
Created 8 option(s)
Command create-jvm-options executed successfully.
Deploying StrongKey FidoServer ... remote failure: Error occurred during deployment: Exception while loading the app : EJB Container initialization error. Please see server.log for more details.
Command deploy failed.
Done!

-------------------------------------------------------------------------------------------------------
Begining here is the log of PAYARA

[2020-02-07T14:30:12.974+0000] [Payara 4.1] [INFOS] [SKCE-MSG-1052] [SKFS] [tid: _ThreadID=55 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1581085812974] [levelValue: 800] [[
  SKCE-MSG-1052: Default configuration properties: 
	skfs.cfg.property.1.applicationid: https://fidodemo.strongauth.com/app.json
	skfs.cfg.property.db.keyhandle.encrypt: false
	skfs.cfg.property.db.keyhandle.encrypt.saka.domainid: 1
	skfs.cfg.property.db.signature.rowlevel.add: true
	skfs.cfg.property.db.signature.rowlevel.verify: true
	skfs.cfg.property.entropylength: 512
	skfs.cfg.property.fido.userid.length: 32
	skfs.cfg.property.fido.usermetadata: Local
	skfs.cfg.property.fido2.user.settings.version: 1
	skfs.cfg.property.fidokeys.flush.cutofftime.seconds: 30
	skfs.cfg.property.fidokeys.flush.frequency.seconds: 5
	skfs.cfg.property.jdbc.dbcommitsize: 200
	skfs.cfg.property.jdbc.dbfetchsize: 500
	skfs.cfg.property.jdbc.dbprocesssize: 10000
	skfs.cfg.property.jdbc.jndiname: jdbc/strongkeylite
	skfs.cfg.property.junit.ldape.url.soap: https://fidodemo.strongauth.com/ldape/LDAPEServlet?wsdl
	skfs.cfg.property.junit.skee.url.soap: https://fidodemo.strongauth.com/skee/SKEEServlet?wsdl
	skfs.cfg.property.junit.skfe.testuser: fidotestuser
	skfs.cfg.property.junit.skfe.url.rest: https://fidodemo.strongauth.com/skfe/rest
	skfs.cfg.property.junit.skfe.url.soap: https://fidodemo.strongauth.com/skfe/soap?wsdl
	skfs.cfg.property.junit.skse.url.soap: https://fidodemo.strongauth.com/skse/SKSEServlet?wsdl
	skfs.cfg.property.messaging.blpsleeptime: 60
	skfs.cfg.property.messaging.timediff: 60
	skfs.cfg.property.pkix.validate: true
	skfs.cfg.property.pkix.validate.default.truststore: /usr/local/strongkey/skce/etc/pkix-truststore.jceks
	skfs.cfg.property.pkix.validate.default.truststore.password: **********
	skfs.cfg.property.pkix.validate.method: truststore
	skfs.cfg.property.retrieve.tld: false
	skfs.cfg.property.runtime.localdemo: true
	skfs.cfg.property.saka.encryption.wsdlsuffix: /strongkeyliteWAR/EncryptionService?wsdl
	skfs.cfg.property.signsuffix: -SIGN
	skfs.cfg.property.skfshome: /usr/local/strongkey/skfs
	skfs.cfg.property.standalone.fidoengine: true
	skfs.cfg.property.standalone.signingkeystore.password: **********
	skfs.cfg.property.userkeypointers.flush.cutofftime.seconds: 300
	skfs.cfg.property.userkeypointers.flush.frequency.seconds: 5
	skfs.cfg.property.usersession.flush.cutofftime.seconds: 30
	skfs.cfg.property.usersession.flush.frequency.seconds: 5]]

[2020-02-07T14:30:12.975+0000] [Payara 4.1] [INFOS] [SKCE-MSG-1053] [SKFS] [tid: _ThreadID=55 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1581085812975] [levelValue: 800] [[
  SKCE-MSG-1053: Configuration log message: SKFS_HOME is: /usr/local/strongkey/skfs]]

[2020-02-07T14:30:12.975+0000] [Payara 4.1] [AVERTISSEMENT] [SKCE-MSG-1053] [SKFS] [tid: _ThreadID=55 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1581085812975] [levelValue: 900] [[
  SKCE-MSG-1053: Configuration log message: There is no skfs-configuration.properties in the SKFS_HOME directory; using system-wide skfs-configuration.properties]]

[2020-02-07T14:30:12.976+0000] [Payara 4.1] [INFOS] [SKCE-MSG-1054] [SKFS] [tid: _ThreadID=55 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1581085812976] [levelValue: 800] [[
  SKCE-MSG-1054: Over-riding properties in SKCE_HOME: 
	skfs.cfg.property.1.applicationid: https://fidodemo.strongauth.com/app.json
	skfs.cfg.property.db.keyhandle.encrypt: false
	skfs.cfg.property.db.keyhandle.encrypt.saka.domainid: 1
	skfs.cfg.property.db.signature.rowlevel.add: true
	skfs.cfg.property.db.signature.rowlevel.verify: true
	skfs.cfg.property.entropylength: 512
	skfs.cfg.property.fido.userid.length: 32
	skfs.cfg.property.fido.usermetadata: Local
	skfs.cfg.property.fido2.user.settings.version: 1
	skfs.cfg.property.fidokeys.flush.cutofftime.seconds: 30
	skfs.cfg.property.fidokeys.flush.frequency.seconds: 5
	skfs.cfg.property.jdbc.dbcommitsize: 200
	skfs.cfg.property.jdbc.dbfetchsize: 500
	skfs.cfg.property.jdbc.dbprocesssize: 10000
	skfs.cfg.property.jdbc.jndiname: jdbc/strongkeylite
	skfs.cfg.property.junit.ldape.url.soap: https://fidodemo.strongauth.com/ldape/LDAPEServlet?wsdl
	skfs.cfg.property.junit.skee.url.soap: https://fidodemo.strongauth.com/skee/SKEEServlet?wsdl
	skfs.cfg.property.junit.skfe.testuser: fidotestuser
	skfs.cfg.property.junit.skfe.url.rest: https://fidodemo.strongauth.com/skfe/rest
	skfs.cfg.property.junit.skfe.url.soap: https://fidodemo.strongauth.com/skfe/soap?wsdl
	skfs.cfg.property.junit.skse.url.soap: https://fidodemo.strongauth.com/skse/SKSEServlet?wsdl
	skfs.cfg.property.messaging.blpsleeptime: 60
	skfs.cfg.property.messaging.timediff: 60
	skfs.cfg.property.pkix.validate: true
	skfs.cfg.property.pkix.validate.default.truststore: /usr/local/strongkey/skce/etc/pkix-truststore.jceks
	skfs.cfg.property.pkix.validate.default.truststore.password: **********
	skfs.cfg.property.pkix.validate.method: truststore
	skfs.cfg.property.retrieve.tld: false
	skfs.cfg.property.runtime.localdemo: true
	skfs.cfg.property.saka.encryption.wsdlsuffix: /strongkeyliteWAR/EncryptionService?wsdl
	skfs.cfg.property.signsuffix: -SIGN
	skfs.cfg.property.skfshome: /usr/local/strongkey/skfs
	skfs.cfg.property.standalone.fidoengine: true
	skfs.cfg.property.standalone.signingkeystore.password: **********
	skfs.cfg.property.userkeypointers.flush.cutofftime.seconds: 300
	skfs.cfg.property.userkeypointers.flush.frequency.seconds: 5
	skfs.cfg.property.usersession.flush.cutofftime.seconds: 30
	skfs.cfg.property.usersession.flush.frequency.seconds: 5]]

[2020-02-07T14:30:13.575+0000] [Payara 4.1] [GRAVE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=55 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1581085813575] [levelValue: 1000] [[
  Exception while invoking class org.glassfish.ejb.startup.EjbDeployer load method
java.lang.RuntimeException: EJB Container initialization error
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:237)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:290)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:100)
	at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:209)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:318)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:497)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:508)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:570)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:562)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:561)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1469)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
	at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:407)
	at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandSimpInMultOut(CommandResource.java:234)
	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
	at org.glassfish.admin.rest.adapter.JerseyContainerCommandService$3.service(JerseyContainerCommandService.java:173)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:179)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:483)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
	at org.bouncycastle.jcajce.provider.ProvSecureHash$MD5.configure(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	at com.strongkey.skfs.utilities.skfsCommon.<clinit>(skfsCommon.java:213)
	at com.strongkey.skfs.txbeans.startServices.<init>(startServices.java:27)
	at com.strongkey.skfs.txbeans.__EJB31_Generated__startServices__Intf____Bean__.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.sun.ejb.containers.BaseContainer.instantiateOptionalEJBLocalBusinessObjectImpl(BaseContainer.java:3890)
	at com.sun.ejb.containers.AbstractSingletonContainer.initializeHome(AbstractSingletonContainer.java:224)
	at com.sun.ejb.containers.SingletonContainerFactory.createContainer(SingletonContainerFactory.java:72)
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:225)
	... 65 more
Caused by: java.lang.NullPointerException
	at org.bouncycastle.crypto.fips.FipsStatus.getJarFile(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsStatus.access$000(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsStatus$1.run(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsStatus$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.bouncycastle.crypto.fips.FipsStatus.checksumValidate(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsStatus.isReady(Unknown Source)
	at org.bouncycastle.crypto.CryptoServicesRegistrar.getDefaultMode(Unknown Source)
	at org.bouncycastle.crypto.CryptoServicesRegistrar.<clinit>(Unknown Source)
	... 81 more
]]

**Comment by push2085** [comment]
Hi @Cedric4real ,

Can you give us a little more information to debug the problem. 
1) What are the specs of the VM (Memory, HDD space , CPU, exact ubuntu version). Its quite possible that this vm is the minimal that Azure offers and does not have enough disk space or memory to run all these components. I have seen this happen once before when the memiry allocation was wrong. Run the following command and post that output as well:
shell> df -h

shell> vmstat -s | head

2) Can you also upload contents of **/var/log/messages** which may have some additional messages that might point to the problem.

**Comment by Cedric4real** [comment]
Hello @push2085, 

Thank you for your quick reply! 


I am using CENT-OS 7 here is the output for the two commands: 

[root@server Strongkey]# df -h
Sys. de fichiers    Taille Utilisé Dispo Uti% Monté sur
/dev/mapper/cl-root    38G     36G  1,4G  97% /
devtmpfs              1,9G       0  1,9G   0% /dev
tmpfs                 1,9G     29M  1,9G   2% /dev/shm
tmpfs                 1,9G    9,1M  1,9G   1% /run
tmpfs                 1,9G       0  1,9G   0% /sys/fs/cgroup
/dev/sda1            1014M    174M  841M  18% /boot
/dev/mapper/cl-home    19G    665M   18G   4% /home
tmpfs                 378M    4,0K  378M   1% /run/user/42
tmpfs                 378M     20K  378M   1% /run/user/0
/dev/sr0              4,1G    4,1G     0 100% /run/media/root/CentOS 7 x86_64
overlay                38G     36G  1,4G  97% /var/lib/docker/overlay2/7795feeb36de479b160443401d29dc247445ecf4ffbb09e35b154f3c18aada6b/merged 
------------------------------------------------------------------------------------------------------

[root@server Strongkey]# vmstat -s | head
      3865552 K total memory
      2942164 K used memory
      1965048 K active memory
      1248448 K inactive memory
       113928 K free memory
           40 K buffer memory
       809420 K swap cache
      4063228 K total swap
       203780 K used swap
      3859448 K free swap 

--------------------------------------------------------------------------------------------------------

Here is the content of var/log/messages:


Feb  7 18:18:01 server systemd: Started Session 130 of user root.
Feb  7 18:18:01 server systemd: Starting Session 130 of user root.
Feb  7 18:18:45 server systemd: Stopping Hardware RNG Entropy Gatherer Daemon...
Feb  7 18:18:45 server systemd: Started Hardware RNG Entropy Gatherer Daemon.
Feb  7 18:18:45 server systemd: Starting Hardware RNG Entropy Gatherer Daemon...
Feb  7 18:18:45 server rngd: Initalizing available sources
Feb  7 18:18:45 server rngd: Failed to init entropy source 0: Hardware RNG Device
Feb  7 18:18:45 server rngd: Enabling RDSEED rng support
Feb  7 18:18:45 server rngd: Initalizing entropy source Intel RDRAND Instruction RNG
Feb  7 18:18:46 server rngd: Enabling JITTER rng support
Feb  7 18:18:46 server rngd: Initalizing entropy source JITTER Entropy generator
Feb  7 18:19:16 server systemd: Reloading.
Feb  7 18:19:16 server systemd-sysv-generator[113210]: Overwriting existing symlink /run/systemd/generator.late/mysql.service with real service
Feb  7 18:19:16 server systemd: [/usr/lib/systemd/system/docker.service:38] Unknown lvalue 'TasksMax' in section 'Service'
Feb  7 18:19:16 server systemd: [/usr/lib/systemd/system/containerd.service:16] Unknown lvalue 'TasksMax' in section 'Service'
Feb  7 18:19:17 server systemd: Reloading.
Feb  7 18:19:17 server systemd-sysv-generator[113257]: Overwriting existing symlink /run/systemd/generator.late/mysql.service with real service
Feb  7 18:19:17 server systemd: [/usr/lib/systemd/system/docker.service:38] Unknown lvalue 'TasksMax' in section 'Service'
Feb  7 18:19:17 server systemd: [/usr/lib/systemd/system/containerd.service:16] Unknown lvalue 'TasksMax' in section 'Service'
Feb  7 18:19:24 server dhclient[1286]: DHCPREQUEST on ens34 to 172.16.47.254 port 67 (xid=0x16b87f05)
Feb  7 18:19:24 server dhclient[1286]: DHCPACK from 172.16.47.254 (xid=0x16b87f05)
Feb  7 18:19:24 server NetworkManager[743]: <info>  [1581099564.1785] dhcp4 (ens34):   address 172.16.47.129
Feb  7 18:19:24 server NetworkManager[743]: <info>  [1581099564.1785] dhcp4 (ens34):   plen 24 (255.255.255.0)
Feb  7 18:19:24 server NetworkManager[743]: <info>  [1581099564.1786] dhcp4 (ens34):   server identifier 172.16.47.254
Feb  7 18:19:24 server NetworkManager[743]: <info>  [1581099564.1786] dhcp4 (ens34):   lease time 1800
Feb  7 18:19:24 server NetworkManager[743]: <info>  [1581099564.1786] dhcp4 (ens34):   nameserver '172.16.47.1'
Feb  7 18:19:24 server NetworkManager[743]: <info>  [1581099564.1786] dhcp4 (ens34):   domain name 'localdomain'
Feb  7 18:19:24 server systemd: Starting Network Manager Script Dispatcher Service...
Feb  7 18:19:24 server NetworkManager[743]: <info>  [1581099564.1786] dhcp4 (ens34): state changed bound -> bound
Feb  7 18:19:24 server dbus[724]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Feb  7 18:19:24 server dhclient[1286]: bound to 172.16.47.129 -- renewal in 760 seconds.
Feb  7 18:19:24 server dbus[724]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Feb  7 18:19:24 server nm-dispatcher: req:1 'dhcp4-change' [ens34]: new request (11 scripts)
Feb  7 18:19:24 server nm-dispatcher: req:1 'dhcp4-change' [ens34]: start running ordered scripts...
Feb  7 18:19:24 server systemd: Started Network Manager Script Dispatcher Service.
Feb  7 18:19:36 server systemd: Reloading.
Feb  7 18:19:36 server systemd-sysv-generator[113713]: Overwriting existing symlink /run/systemd/generator.late/mysql.service with real service
Feb  7 18:19:36 server systemd: [/usr/lib/systemd/system/docker.service:38] Unknown lvalue 'TasksMax' in section 'Service'
Feb  7 18:19:36 server systemd: [/usr/lib/systemd/system/containerd.service:16] Unknown lvalue 'TasksMax' in section 'Service'
Feb  7 18:19:36 server systemd: Starting LSB: Init script for Opendj...
Feb  7 18:19:39 server opendjd: Starting OpenDJ 3.0.0 Directory Service: [07/févr./2020:18:19:39 +0000] category=CORE severity=NOTICE msgID=org.opends.messages.core.134 msg=OpenDJ 3.0.0 (build 20160109123031, revision number 185acee3ba68d8da1782007eebacb3701dc996d6) starting up
Feb  7 18:19:40 server opendjd: [07/févr./2020:18:19:40 +0000] category=UTIL severity=NOTICE msgID=org.opends.messages.runtime.21 msg=Installation Directory:  /usr/local/strongkey/OpenDJ-3.0.0
Feb  7 18:19:40 server opendjd: [07/févr./2020:18:19:40 +0000] category=UTIL severity=NOTICE msgID=org.opends.messages.runtime.23 msg=Instance Directory:      /usr/local/strongkey/OpenDJ-3.0.0
Feb  7 18:19:40 server opendjd: [07/févr./2020:18:19:40 +0000] category=UTIL severity=NOTICE msgID=org.opends.messages.runtime.17 msg=JVM Information: 1.8.0_121-b13 by Oracle Corporation, 64-bit architecture, 880279552 bytes heap size
Feb  7 18:19:40 server opendjd: [07/févr./2020:18:19:40 +0000] category=UTIL severity=NOTICE msgID=org.opends.messages.runtime.18 msg=JVM Host: server.cryptoneodemo.com, running Linux 3.10.0-514.el7.x86_64 amd64, 3958325248 bytes physical memory size, number of processors available 4
Feb  7 18:19:40 server opendjd: [07/févr./2020:18:19:40 +0000] category=UTIL severity=NOTICE msgID=org.opends.messages.runtime.19 msg=JVM Arguments: "-Dorg.opends.server.scriptName=start-ds"
Feb  7 18:19:42 server opendjd: [07/févr./2020:18:19:42 +0000] category=PLUGGABLE severity=NOTICE msgID=org.opends.messages.backend.513 msg=The database backend userRoot containing 7 entries has started
Feb  7 18:19:42 server opendjd: [07/févr./2020:18:19:42 +0000] category=EXTENSIONS severity=NOTICE msgID=org.opends.messages.extension.221 msg=DIGEST-MD5 SASL mechanism using a server fully qualified domain name of: server.cryptoneodemo.com
Feb  7 18:19:43 server opendjd: [07/févr./2020:18:19:43 +0000] category=PROTOCOL severity=NOTICE msgID=org.opends.messages.protocol.276 msg=Started listening for new connections on Administration Connector 0.0.0.0 port 4444
Feb  7 18:19:43 server opendjd: [07/févr./2020:18:19:43 +0000] category=PROTOCOL severity=NOTICE msgID=org.opends.messages.protocol.276 msg=Started listening for new connections on LDAP Connection Handler 0.0.0.0 port 1389
Feb  7 18:19:43 server opendjd: [07/févr./2020:18:19:43 +0000] category=CORE severity=NOTICE msgID=org.opends.messages.core.135 msg=The Directory Server has started successfully
Feb  7 18:19:43 server opendjd: [07/févr./2020:18:19:43 +0000] category=CORE severity=NOTICE msgID=org.opends.messages.core.139 msg=The Directory Server has sent an alert notification generated by class org.opends.server.core.DirectoryServer (alert type org.opends.server.DirectoryServerStarted, alert ID org.opends.messages.core-135): The Directory Server has started successfully
Feb  7 18:19:43 server opendjd: [  OK  ]
Feb  7 18:19:43 server systemd: Started LSB: Init script for Opendj.
Feb  7 18:20:01 server systemd: Starting LSB: Debian init script for payara webserver...
Feb  7 18:20:01 server systemd: Started Session 131 of user root.
Feb  7 18:20:01 server systemd: Starting Session 131 of user root.
Feb  7 18:20:20 server glassfishd: Starting Glassfish 4 Application Server: Waiting for domain1 to start ..................
Feb  7 18:20:20 server glassfishd: Successfully started the domain : domain1
Feb  7 18:20:20 server glassfishd: domain  Location: /usr/local/strongkey/payara41/glassfish/domains/domain1
Feb  7 18:20:20 server glassfishd: Log File: /usr/local/strongkey/payara41/glassfish/domains/domain1/logs/server.log
Feb  7 18:20:20 server glassfishd: Admin Port: 4848
Feb  7 18:20:20 server glassfishd: Command start-domain executed successfully.
Feb  7 18:20:20 server glassfishd: [  OK  ]
Feb  7 18:20:20 server systemd: Started LSB: Debian init script for payara webserver.
Feb  7 18:21:02 server systemd: Started Session 132 of user root.
Feb  7 18:21:02 server systemd: Starting Session 132 of user root.

**Comment by push2085** [comment]
Hi @Cedric4real ,

Can you trying creating a new VM and try with newer builds that have been recently uploaded.

**Comment by pattycakelol** [comment]
Hi @Cedric4real,
Are you still encountering this issue?
