### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by swapnilphanse** [StrongKey/fido2#51]
Hello,

While trying to run the simulator I am getting the following error:-

java -jar skfsclient.jar R https://fidocapstone.eastus2.cloudapp.azure.com:8181/ 1 REST HMAC 162a5684336fa6e7 7edd81de1baab6ebcc76ebe3e38f41f4 johndoe https://fidocapstone.eastus2.cloudapp.azure.com:8181

Copyright (c) 2001-2020 StrongAuth, Inc. All rights reserved.

REST Registration test with HMAC
*******************************

Calling preregister @ https://fidocapstone.eastus2.cloudapp.azure.com:8181/skfs/rest/preregister
Exception in thread "main" javax.net.ssl.SSLPeerUnverifiedException: Certificate for <fidocapstone.eastus2.cloudapp.azure.com> doesn't match any of the subject alternative names: []
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:467)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:397)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.strongkey.skfsclient.impl.rest.RestFidoRegister.register(RestFidoRegister.java:112)
	at FidoEngine.main(FidoEngine.java:127)

I tried to run this command using SOAP as well but still getting the following error:-

java -jar skfsclient.jar R https://fidocapstone.eastus2.cloudapp.azure.com:8181 1 SOAP HMAC 162a5684336fa6e7 7edd81de1baab6ebcc76ebe3e38f41f4 johndoe https://fidocapstone.eastus2.cloudapp.azure.com:8181

Copyright (c) 2001-2020 StrongAuth, Inc. All rights reserved.

javax.xml.ws.WebServiceException: Failed to access the WSDL at: https://fidocapstone.eastus2.cloudapp.azure.com:8181/skfs/soap?wsdl. It failed with:
	java.security.cert.CertificateException: No name matching fidocapstone.eastus2.cloudapp.azure.com found.
	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.tryWithMex(RuntimeWSDLParser.java:250)
	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:231)
	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:194)
	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:163)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:348)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:306)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:215)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:196)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:192)
	at com.sun.xml.internal.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:104)
	at javax.xml.ws.Service.<init>(Service.java:77)
	at com.strongkey.skfs.soapstubs.Soap.<init>(Soap.java:50)
	at com.strongkey.skfsclient.impl.soap.SoapFidoRegister.register(SoapFidoRegister.java:78)
	at FidoEngine.main(FidoEngine.java:129)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No name matching fidocapstone.eastus2.cloudapp.azure.com found
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at java.net.URL.openStream(URL.java:1068)
	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.createReader(RuntimeWSDLParser.java:984)
	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.resolveWSDL(RuntimeWSDLParser.java:385)
	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:216)
	... 12 more
Caused by: java.security.cert.CertificateException: No name matching fidocapstone.eastus2.cloudapp.azure.com found
	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:231)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:96)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:462)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:428)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:209)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 28 more
java.lang.Exception: It appears that the site - https://fidocapstone.eastus2.cloudapp.azure.com:8181 - is (1) either down or (2) has no access over specified port or (3) has a digital certificate that is not in your JVM's truststore.  In case of (3), Please include it in the JAVA_HOME/jre/lib/security/cacerts file with the keytool -import command before attempting this operation again.  Please refer to the documentation on skceclient.jar at the above-mentioned URL on how to accomplish this.
	at com.strongkey.skfsclient.impl.soap.SoapFidoRegister.register(SoapFidoRegister.java:85)
	at FidoEngine.main(FidoEngine.java:129)
 Exception: It appears that the site - https://fidocapstone.eastus2.cloudapp.azure.com:8181 - is (1) either down or (2) has no access over specified port or (3) has a digital certificate that is not in your JVM's truststore.  In case of (3), Please include it in the JAVA_HOME/jre/lib/security/cacerts file with the keytool -import command before attempting this operation again.  Please refer to the documentation on skceclient.jar at the above-mentioned URL on how to accomplish this.

Done with Register!

I am trying to run the fido server on Ubuntu VM having 8GB Memory and 15GB HDD.

**Comment by pattycakelol** [comment]
Hi @swapnilphanse,
It seems that the certificate of the FIDO2 Server you are connecting to does not match the hostname in your test.
Please ensure that the CN and hostname are matching.

**Comment by swapnilphanse** [comment]
Hi @pattycakelol ,

Yes. I checked the certificate name and hostname. They were not matching that's why I was getting this error. Thank you for your help.
