### ISSUE TITLE
What is the default password for signingkeystore.bcfks and signingtruststore.bcfks?

### ISSUE THREAD

**Issue by mlruss** [StrongKey/fido2#9]
**Describe the bug**
Following the installation guide, I'm trying to use keymanager.jar to change the default signing keys.  Keymanager.jar requires the passwords to the keystores, but I don't see the password in the documentation.  I tried "changeit" and a few other reasonable guesses, but haven't figured out the correct password. 

**To Reproduce**
1. cd /usr/local/strongkey/keymanager
2. java -jar keymanager.jar listaccesskeys ../skfs/keystores/signingkeystore.bcfks changeit
Error message:
Exception in thread "main" java.io.IOException: BCFKS KeyStore corrupted: MAC calculation failed.
        at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.verifyMac(Unknown Source)
        at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.engineLoad(Unknown Source)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at Main.listaccesskeys(Main.java:78)
        at Main.main(Main.java:55)
[strongkey@fido keymanager]$

**Expected behavior**
It would be helpful to include the password in the Installation Guide

**Screenshots**
n/a

**Desktop (please complete the following information):**
Running on Amazon Linux, OpenJDK 8

**Comment by max-smyth** [comment]
Thanks for reporting the issue. The default keystore password is 
Abcd1234!

We'll update the documentation to make sure this is included.

**Comment by mlruss** [comment]
Perfect, thanks!
